GearAdd = (vehicle player);
GearAdd addWeapon 'M4SPR';
GearAdd addMagazine '100Rnd_556x45_BetaCMag';
GearAdd addMagazine '100Rnd_556x45_BetaCMag';
GearAdd addMagazine '100Rnd_556x45_BetaCMag';
GearAdd addMagazine 'Skin_Sniper1_DZ';
GearAdd addMagazine 'ItemMorphine';
GearAdd addMagazine 'ItemBloodbag';
GearAdd addMagazine 'ItemSodaPepsi';
GearAdd addMagazine 'FoodSteakCooked';
GearAdd addWeapon 'revolver_gold_EP1';
GearAdd addMagazine '6Rnd_45ACP';
GearAdd addMagazine '6Rnd_45ACP';
GearAdd addMagazine '6Rnd_45ACP';
GearAdd addMagazine '6Rnd_45ACP';
GearAdd addMagazine 'ItemBandage';
GearAdd addMagazine 'ItemBandage';
GearAdd addWeapon 'Binocular_Vector';
GearAdd addWeapon 'ItemCompass';
GearAdd addWeapon 'ItemMap';
GearAdd addWeapon 'ItemWatch';
GearAdd addWeapon 'ItemHatchet';
GearAdd addWeapon 'ItemKnife';
GearAdd addWeapon 'Itemmatchbox';
GearAdd addWeapon 'Itemetool';
GearAdd addWeapon 'Itemtoolbox';
GearAdd addBackpack 'DZ_LargeGunBag_EP1';
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBloodbag', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemEpinephrine', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemSodaPepsi', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemBandage', 4];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['FoodSteakCooked', 2];
(Unitbackpack GearAdd) addMagazineCargoGlobal ['ItemMorphine', 2];